### ISSUE TITLE
Pulling logs via OpenTelemetry collector

### ISSUE THREAD

**Issue by yevsh** [FWinkler79/spring3-observability#1]
First of all thank you for this project it might be wha i need.

Secondly, sorry for using 'issue' to get clarifications .

I want OpenTelemetry collect logs that my springboot 3.2 app produces (runs in container in k8s).

1. Is it necessary to create Appender for logs (no out of the box support)?
2. Is it required to have opentelemetry-exporter-otlp-logs? I don't want to 'push' logs to OpenTelemetry i want the OpenTelemetry to scrap the logs from application.
3. in resources folder there many different log configuration which is required?

Thank you

**Comment by FWinkler79** [comment]
Hi there, sorry, for the late reply. 

You might want to have a look at this discussion: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/9322

Ad 1: 
There is a Logback Appender provided by OTEL, but you need to configure it and I think the design is slightly problematic, since it requires you to defines some global OTEL SDK instance and you need to do it early in the lifecycle of the application.
My implementation simply creates a new SDK instance within the Logback Appender. But that's a matter of taste, I guess.
So you can use an implementation like the one I implemented here, or you use the OTEL Logback Appender.

Ad 2: 
No, you don't have to use the push exporter. You can also configure the collector to scrape data from your applications. For example, there is the [prometheus receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusreceiver) for metrics that can scrape your metrics endpoints on the applications.
When you say you want to scrape logs, the question would be how you expose them? Via a REST endpoint, or a different way. Have a look at the different [receivers](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver) that are provided by the OTEL collector contrib version. Maybe you will find something that fits your technology stack.

Ad 3: 
The `resources` folder contains different samples of appender configurations. Each file configures a different appender.
They are all referenced from a single file: `logback-spring.xml` - that's the file where you configure the logback stack (appenders, log formats, etc.) for a Spring Boot application. If you used my Logback Appender implementation for OTEL, you would at least need the following files:

* `logback-spring.xml`
* `opentelemetry-appender.xml`

Hope that helps.
